import Link from 'next/link';
import React from 'react';


export default function Head() {
  return (
    <>
      <title>Alebiosu Gbolahan  | Portfolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
